### ISSUE TITLE
Initialization step is not working

### ISSUE THREAD

**Issue by wanyay** [Jigsaw-Code/outline-client#1484]
**Describe the bug**
Initialization step is not working

**Screenshots**
![Screenshot from 2022-11-21 22-13-46](https://user-images.githubusercontent.com/14345020/203097288-07816133-011a-462a-a8c7-cd112230be21.png)
![Screenshot from 2022-11-22 12-10-52](https://user-images.githubusercontent.com/14345020/203233819-72e985c0-4609-4621-8fac-e8439652b7ef.png)

**Client System (please complete the following information):**
 - Outline Client Version [Linux 1.8.1]
 - Your Operating System: [Manjaro Linux 22]

**Comment by persian85** [comment]
Correct I have this exact problem too.

**Comment by idev-software-group** [comment]
It is better to use the AppImage version to use the application, so that you don't have any conflict with loading the Command Line Terminal to launch it. for more information please email us ( we are representative of Outline in IRAN ) : **[idev.softwaregroup@gmail.com](mailto:idev.softwaregroup@gmail.com)**

**Comment by persian85** [comment]
Actually I tested the AppImage and got this error too.

**Comment by jyyi1** [comment]
Hi @wanyay @persian85 , sorry about the inconvenience. From the error message, it is because we are failed to lock the temporary installation scripts using `chattr -R -o /tmp/xxxxx`, error message is `chattr operation not supported while reading flags on /tmp/xxxxx`. Could you please double confirm that this command is working on your machine and the paths in `/tmp/` are not symbolic links?

**Comment by wanyay** [comment]
@jyyi1 Sorry for the late reply, I have checked the `chattr` command is not working my machine.
Could you please share me if you have a quick solution for it.?

![Screenshot from 2022-12-17 21-57-00](https://user-images.githubusercontent.com/14345020/208249263-5ec5618c-11db-4dde-8c0f-cf71f16984dd.png)

**Comment by jyyi1** [comment]
@wanyay Maybe because your `/tmp/` folder is a symbolic link? Anyway, here is a workaround:

1. download the contents in "https://github.com/Jigsaw-Code/outline-client/tree/linux-v1.8.1/tools/outline_proxy_controller/dist" and `cd` into the folder
2. Make sure `install_linux_service.sh` and `OutlineProxyController` are executable (`chmod +x`)
3. Run `sudo ./install_linux_service.sh <your-linux-username>`, for example, if you linux username is `wanyay`, please run `sudo ./install_linux_service.sh wanyay`
4. After the installation script runs successfully, please launch Outline and try to connect

**Comment by simakazi** [comment]
I had the same problem because my /tmp was mounted on tmpfs. Removed mount point from /etc/fstab and initialization processed completed just fine.

**Comment by VladimirCores** [comment]
> I had the same problem because my /tmp was mounted on tmpfs. Removed mount point from /etc/fstab and initialization processed completed just fine.

Could you help with it? How to remove mount point?

**Comment by searayeah** [comment]
In Manjaro /tmp is  by default mounted on tmpfs  `tmpfs    /tmp    tmpfs   defaults,noatime,mode=1777 0 0`.
This might be the problem.

**Comment by xqyww123** [comment]
actually the command lines work fine if I remove the chattr, so why not make it optional? like wrap it by a `(chattr ... || true)`?

**Comment by xqyww123** [comment]
See how I fixed the issue XD

```
$ cd /usr/bin
$ sudo mv chattr chattr2
$ sudo cp true chattr
### do the initialization
$ sudo cp chattr2 chattr
```

**Comment by jyyi1** [comment]
Hi @xqyww123 sorry about the inconvenience, there are some security reasons why we have to use `chattr`. Also we only officially support **Ubuntu (or some Debian based distro)** for now, we will update our website to clearly deliver this message.

We are also working on a standalone command line tool for Linux, that doesn't require any installations, and it will also support more distro's as well.

**Comment by jonathanpa** [comment]
@jyyi1 I have installed outline_proxy_controller successfully on my machine as described in this comment https://github.com/Jigsaw-Code/outline-client/issues/1484#issuecomment-1358019993 but when running the outline client from the AppImage file I still have the same problem.

I see there is a new service outline_proxy_controller.service added to my system and the service is running when I check with systemctl status but are we sure that the outline app image executable file is using this service ?

Or may be because I run the outline client the wrong way ?

**Comment by jyyi1** [comment]
Hi @jonathanpa , yes Outline client will communicate with `outline_proxy_controller.service` through Unix socket `/var/run/outline_controller`. Please make sure your current account is able to `rw` this socket. Also, please check whether `outline_proxy_controller.service` is running normally by this command `journalctl -u outline_proxy_controller`.

**Comment by zeretrelle** [comment]
> @wanyay Maybe because your `/tmp/` folder is a symbolic link? Anyway, here is a workaround:
> 
>     1. download the contents in "https://github.com/Jigsaw-Code/outline-client/tree/linux-v1.8.1/tools/outline_proxy_controller/dist" and `cd` into the folder
> 
>     2. Make sure `install_linux_service.sh` and `OutlineProxyController` are executable (`chmod +x`)
> 
>     3. Run `sudo ./install_linux_service.sh <your-linux-username>`, for example, if you linux username is `wanyay`, please run `sudo ./install_linux_service.sh wanyay`
> 
>     4. After the installation script runs successfully, please launch Outline and try to connect

It's not working on my Fedora 37 installation.

I get these errors
>./install_linux_service.sh: line 8: syntax error near unexpected token `newline'
>./install_linux_service.sh: line 8: `<!DOCTYPE html>'

**Comment by jyyi1** [comment]
@zeretrelle I'm not sure about this error because line 8 of `./install_linux_service.sh` is a comment line. Please double check the line ending (make sure they are linux line endings instead of Windows line endings), also please make sure you can execute the bash scripts in your system.

**Comment by zeretrelle** [comment]
> @zeretrelle I'm not sure about this error because line 8 of `./install_linux_service.sh` is a comment line. Please double check the line ending (make sure they are linux line endings instead of Windows line endings), also please make sure you can execute the bash scripts in your system.

Is the document /install_linux_service.sh supposed to start with <!DOCTYPE html> ?

**Comment by zeretrelle** [comment]
> @zeretrelle I'm not sure about this error because line 8 of `./install_linux_service.sh` is a comment line. Please double check the line ending (make sure they are linux line endings instead of Windows line endings), also please make sure you can execute the bash scripts in your system.

The  install_linux_service.sh files starts with with ~<!DOCTYPE html>!~ for some reason..

**Comment by VACdotCS** [comment]
1) Download 3 files from https://github.com/Jigsaw-Code/outline-client/tree/linux-v1.8.1/tools/outline_proxy_controller/dist

2) Make files OutlieProxyController and install_linux_service.sh executable with chmod +x

3) Run sudo ./outline_linux_service.sh {linux_username}

4) Then go to $HOME/.config/Outline and create Empty File with name “connection_store“

5) After that cd /var/run and run sudo chown {linux_username}:outlinevpn outline_controller

6) Try to connect

**Comment by jahrec** [comment]
> 1. Download 3 files from https://github.com/Jigsaw-Code/outline-client/tree/linux-v1.8.1/tools/outline_proxy_controller/dist
> 2. Make files OutlieProxyController and install_linux_service.sh executable with chmod +x
> 3. Run sudo ./outline_linux_service.sh {linux_username}
> 4. Then go to $HOME/.config/Outline and create Empty File with name “connection_store“
> 5. After that cd /var/run and run sudo chown {linux_username}:outlinevpn outline_controller
> 6. Try to connect

thanks a lot!!!
that works for me

**Comment by adequacy1** [comment]
> 3. Run sudo ./outline_linux_service.sh {linux_username}

There is no such file. There is install_linux_service.sh .

**Comment by jyyi1** [comment]
> > 3. Run sudo ./outline_linux_service.sh {linux_username}
> 
> There is no such file. There is install_linux_service.sh .

Yes, this is the correct script name.
