### ISSUE TITLE
windows client: cannot rename TAP device when the new device has non-Latin characters

### ISSUE THREAD

**Issue by yywudi** [Jigsaw-Code/outline-client#291]
Hi

I just download the latest windows client v1.2.12.
my windows host is running Windows Server 2008 R2 64bit.

during installation, it can create a new Tap device, but seems can't rename or next step configuration.
Outline Setup will report "Could not rename TAP device." at the end.

![outline_v1 2 12_install_fail](https://user-images.githubusercontent.com/8049984/45858548-88088480-bd90-11e8-8082-1d9d12992ffb.png)

when I configure & connect to a server, it then always report the "Not able to configure routing tables successfully"

I tried to:
1, manually rename the tap device to "outline-tap0", then the "Not able to configure routing tables successfully" error will not observe but the tap device can't receive any data. that is, connection is established, but the routing table seems not configured correctly as from "route print" the tap device IP is the invalid "169.254.xx.xx"
2, manually configure the tap IPv4 address as 10.0.85.12/255.255.255.0/10.0.85.1(GW), still the same issue that no data received in the tap NIC.

**Comment by trevj** [comment]
Hi @yywudi and thanks for trying Outline! I'm afraid we don't support Windows Server 2008. Can you confirm you're running Windows 2008? I wouldn't have even expected the client to start on Windows Server 2008.

**Comment by trevj** [comment]
@yywudi Apologies, I see now that Windows Server 2008 is basically Windows 7. I can see that the majority of TAP device install failures occur on Windows 7 but I'm afraid right now we don't really know why.

**Comment by trevj** [comment]
@yywudi This may be related to administrator permissions. Doing some testing just now I can see that on Windows 7 the system doesn't necessarily prompt for admin permissions - it does on Windows 8 and 10. This might explain many of the errors we've been seeing.

When you ran the installer, were you logged in as an administrator user?

**Comment by lgg** [comment]
@trevj hmm, what if trouble is in https://github.com/Jigsaw-Code/outline-client/blob/e61bf13b4e8deaec3bd0912bc75ac6c0f8605c9e/electron/add_tap_device.bat#L50

and `%DEVICE_DIFF%` is wrong? 

I just checked my error screen: 
![image](https://user-images.githubusercontent.com/12018713/45924513-a7c3b800-bf0a-11e8-868d-b65aa25d55c5.png)

And TapAdapter names:
![image](https://user-images.githubusercontent.com/12018713/45924521-cf1a8500-bf0a-11e8-8a3e-ab5615d7b4dc.png)


It's different

**Comment by lgg** [comment]
Deleted OutLine client
Deleted TapAdapters
Reboot system
Check NetConnectionIDs:
```
C:\Users\Фёдор>wmic nic get netconnectionid /format:list | findstr "="
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=Подключение по локальной сети
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=Беспроводное сетевое соединение
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=Беспроводное сетевое соединение 2
NetConnectionID=
NetConnectionID=VirtualBox Host-Only Network
NetConnectionID=VirtualBox Host-Only Network #2
NetConnectionID=
NetConnectionID=
NetConnectionID=VMware Network Adapter VMnet1
NetConnectionID=VMware Network Adapter VMnet8
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
```

Install Outline Client v1.2.12:

```
C:\Users\Фёдор>wmic nic get netconnectionid /format:list | findstr "="
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=Подключение по локальной сети
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=Беспроводное сетевое соединение
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=Беспроводное сетевое соединение 2
NetConnectionID=Подключение по локальной сети 3
NetConnectionID=
NetConnectionID=VirtualBox Host-Only Network
NetConnectionID=VirtualBox Host-Only Network #2
NetConnectionID=
NetConnectionID=
NetConnectionID=VMware Network Adapter VMnet1
NetConnectionID=VMware Network Adapter VMnet8
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
NetConnectionID=
```

Trying to check powershell command:

![image](https://user-images.githubusercontent.com/12018713/45924587-bf03a500-bf0c-11e8-9885-eef58d955c8f.png)

Maybe Encoding problem?

**Comment by lgg** [comment]
Hmm, if i manually renamed:
`netsh interface set interface name = "Подключение по локальной сети 3" newname = "outline-tap0"`

Outline client can connect, but my IP still old.

**Comment by trevj** [comment]
@lgg This is extremely useful, thank you very much for the detailed report. It looks like the installer has issues when the new device name is not in English; I will do some testing and report back here exactly what's happening.

**Comment by trevj** [comment]
@yywudi OK, thanks. I think your problem is related to what @lgg describes. Administrator permissions in Windows 7 is something I will track separately.

**Comment by yywudi** [comment]
Yes, I do follow @lgg 's suggestion, manually rename tap/set static ip&dns that follow the https://github.com/Jigsaw-Code/outline-client/blob/e61bf13b4e8deaec3bd0912bc75ac6c0f8605c9e/electron/add_tap_device.bat#L49  then everything is working fine.
besides, my windows server 2008 is running English OS, so OS language seems not the key. just the administrator permission issue.

**Comment by trevj** [comment]
@lgg and @yywudi FYI, I just merged https://github.com/Jigsaw-Code/outline-client/pull/301 which I hope to include in the next version of Outline for Windows, later this week.

**Comment by lgg** [comment]
@trevj i just tried to install windows-v1.2.14 and still got this error: 

New network adapter still called: "Подключение по локальной сети 5"

![image](https://user-images.githubusercontent.com/12018713/46627286-a87f5f80-cb42-11e8-8b0f-9e450eb2bd3e.png)

**Comment by trevj** [comment]
@lgg Thanks for trying again - sorry to hear it still doesn't work.

That device name is quote long - I think the latest release (pushed just now) may address it (looking at the screenshot above in https://github.com/Jigsaw-Code/outline-client/issues/291#issuecomment-423793557 the name **does** seem to be truncated):
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.2.16

I'd love to hear if this new release works for you.

**Comment by yywudi** [comment]
![outline-1 2 16-fail](https://user-images.githubusercontent.com/8049984/47003853-c4968880-d162-11e8-9adb-8694c67bfefc.png)

newly install v1.2.16. report different error but still can't rename the tap device
